'use strict';
const mongoose = require('mongoose');

const AgentSchema = new mongoose.Schema({
  name: String,
  type: { type: String, enum: ['orchestrator', 'llm', 'transform'] },
}, { _id: false });

const LineItemSchema = new mongoose.Schema({
  label:      String,
  detail:     String,
  value:      Number,
  isDiscount: { type: Boolean, default: false },
}, { _id: false });

const QuoteSchema = new mongoose.Schema({
  quoteId:       { type: String, required: true, unique: true, uppercase: true },

  // Client info (captured at gate — no account required)
  clientName:    { type: String, required: true },
  clientEmail:   { type: String, required: true, lowercase: true },
  clientCompany: { type: String, default: '' },

  // Optional linked user account
  userId:        { type: mongoose.Schema.Types.ObjectId, ref: 'User', default: null },

  // Request
  request: { type: String, required: true },

  // Analysis (extracted from workflow by Claude)
  analysis: {
    total_agents:     Number,
    llm_nodes:        Number,
    transformations:  Number,
    complexity:       Number,
    complexity_label: String,
    workflow_summary: String,
    execution_context:String,
    agents:           [AgentSchema],
  },

  // Workflow (generated by Claude — locked until payment)
  workflow: {
    json:         { type: mongoose.Schema.Types.Mixed, default: null },
    summary:      { type: String, default: '' },
    mermaid:      { type: String, default: '' },
    docs:         { type: String, default: '' },
    generatedAt:  { type: Date, default: null },
  },
  workflowLocked: { type: Boolean, default: true },

  // Pricing
  plan:            { type: String, enum: ['whitelabel', 'recurring', 'payg'], required: true },
  supportContract: { type: String, default: null },
  selectedTierId:  { type: String, default: 't2' },
  hostedLLMs:      { type: Boolean, default: true },
  ownKeys: {
    openai:  { type: Boolean, default: false },
    claude:  { type: Boolean, default: false },
    gemini:  { type: Boolean, default: false },
  },
  price:       { type: String  },   // display string e.g. "$1,200/mo"
  buildPrice:  { type: Number  },   // numeric for accounting
  setupFee:    { type: Number, default: null },
  lineItems:   [LineItemSchema],
  configVersion: { type: Number },

  // Status flow: draft → pending → paid → delivered → cancelled
  analysisStatus: { type: String, default: 'processing', enum: ['processing','ready','failed'] },
  status: {
    type: String,
    enum: ['new', 'clarified', 'analysing', 'draft', 'pending', 'paid', 'delivered', 'cancelled'],
    default: 'new',
  },

  // WF1 output — saved when Agent 1 callback arrives
  clarification: { type: mongoose.Schema.Types.Mixed, default: null },

  // Timing — for stuck-quote detection
  wf1SentAt:       { type: Date, default: null },
  wf1CompletedAt:  { type: Date, default: null },
  wf23SentAt:      { type: Date, default: null },

  // Stripe
  stripePaymentIntentId: { type: String, default: '' },
  stripeSessionId:       { type: String, default: '' },
  paidAt:                { type: Date, default: null },

  // Quote expiry
  expiresAt: { type: Date },

  // Change order tracking
  isChangeOrder:   { type: Boolean, default: false },
  originalQuoteId: { type: String, default: null },
  diff:            { type: mongoose.Schema.Types.Mixed, default: null },
}, { timestamps: true });

// Auto-set expiry from config (default 30 days)
QuoteSchema.pre('save', function (next) {
  if (!this.expiresAt) {
    const days = 30;
    this.expiresAt = new Date(Date.now() + days * 24 * 60 * 60 * 1000);
  }
  next();
});

QuoteSchema.index({ clientEmail: 1 });
QuoteSchema.index({ status: 1 });
QuoteSchema.index({ createdAt: -1 });

module.exports = mongoose.model('Quote', QuoteSchema);
